export enum MODELS{
    user = 'users',
    plan = 'plans',
    room = 'rooms',
    slider = 'sliders',
    advertisement = 'advertisements',
    offer = 'offers',
    event = 'events',
    birthDay = 'birthdays',
    category = 'categories',
    product = 'products',
    member = 'members',
    roomBooking = 'roomBooking',
    dayBook = 'dayBook',
    eventBook = 'eventBook',
    auditLog = 'logs',
    memberBooking = 'memberBooking',
    payment = 'payment'
}