export enum MODELS {
  user = 'users',
  plan = 'plans',
  room = 'rooms',
  slider = 'sliders',
  advertisement = 'advertisements',
  offer = 'offers',
  event = 'events',
  birthDay = 'birthdays',
  category = 'categories',
  product = 'products',
  member = 'members',
  roomBooking = 'roomBookings',
  dayBook = 'dayBooks',
  eventBook = 'eventBooks',
  auditLog = 'logs',
  memberBooking = 'memberBookings',
  payment = 'payments',
  location = 'locations',
  package = 'packages',
  setting = 'settings',
}
